// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Embc.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq; using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// LookupEntityInfo
    /// </summary>
    public partial class MicrosoftDynamicsCRMLookupEntityInfo
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMLookupEntityInfo class.
        /// </summary>
        public MicrosoftDynamicsCRMLookupEntityInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMLookupEntityInfo class.
        /// </summary>
        public MicrosoftDynamicsCRMLookupEntityInfo(string entityLogicalName = default(string), string viewId = default(string), string customFilter = default(string), string relationshipName = default(string), string fetchXml = default(string), string layoutJson = default(string), MicrosoftDynamicsCRMPagingInfo pagingInfo = default(MicrosoftDynamicsCRMPagingInfo))
        {
            EntityLogicalName = entityLogicalName;
            ViewId = viewId;
            CustomFilter = customFilter;
            RelationshipName = relationshipName;
            FetchXml = fetchXml;
            LayoutJson = layoutJson;
            PagingInfo = pagingInfo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EntityLogicalName")]
        public string EntityLogicalName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ViewId")]
        public string ViewId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomFilter")]
        public string CustomFilter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RelationshipName")]
        public string RelationshipName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FetchXml")]
        public string FetchXml { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LayoutJson")]
        public string LayoutJson { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PagingInfo")]
        public MicrosoftDynamicsCRMPagingInfo PagingInfo { get; set; }

    }
}
