// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Embc.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq; using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// msdyn_MarketingMetadataUpdateResponse
    /// </summary>
    public partial class MicrosoftDynamicsCRMmsdynMarketingMetadataUpdateResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMmsdynMarketingMetadataUpdateResponse class.
        /// </summary>
        public MicrosoftDynamicsCRMmsdynMarketingMetadataUpdateResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMmsdynMarketingMetadataUpdateResponse class.
        /// </summary>
        public MicrosoftDynamicsCRMmsdynMarketingMetadataUpdateResponse(int? resultCode = default(int?))
        {
            ResultCode = resultCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resultCode")]
        public int? ResultCode { get; set; }

    }
}
