// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Embc.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq; using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// principalobjectaccess
    /// </summary>
    public partial class MicrosoftDynamicsCRMprincipalobjectaccess
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMprincipalobjectaccess class.
        /// </summary>
        public MicrosoftDynamicsCRMprincipalobjectaccess()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMprincipalobjectaccess class.
        /// </summary>
        public MicrosoftDynamicsCRMprincipalobjectaccess(int? timezoneruleversionnumber = default(int?), string principalobjectaccessid = default(string), System.DateTimeOffset? changedon = default(System.DateTimeOffset?), string principalid = default(string), long? versionnumber = default(long?), string objecttypecode = default(string), int? utcconversiontimezonecode = default(int?), string objectid = default(string), string principaltypecode = default(string), int? inheritedaccessrightsmask = default(int?), int? accessrightsmask = default(int?))
        {
            Timezoneruleversionnumber = timezoneruleversionnumber;
            Principalobjectaccessid = principalobjectaccessid;
            Changedon = changedon;
            Principalid = principalid;
            Versionnumber = versionnumber;
            Objecttypecode = objecttypecode;
            Utcconversiontimezonecode = utcconversiontimezonecode;
            Objectid = objectid;
            Principaltypecode = principaltypecode;
            Inheritedaccessrightsmask = inheritedaccessrightsmask;
            Accessrightsmask = accessrightsmask;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timezoneruleversionnumber")]
        public int? Timezoneruleversionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "principalobjectaccessid")]
        public string Principalobjectaccessid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "changedon")]
        public System.DateTimeOffset? Changedon { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "principalid")]
        public string Principalid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "versionnumber")]
        public long? Versionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "objecttypecode")]
        public string Objecttypecode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "utcconversiontimezonecode")]
        public int? Utcconversiontimezonecode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "objectid")]
        public string Objectid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "principaltypecode")]
        public string Principaltypecode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inheritedaccessrightsmask")]
        public int? Inheritedaccessrightsmask { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accessrightsmask")]
        public int? Accessrightsmask { get; set; }

    }
}
