// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Embc.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq; using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// RetrieveEntityResponse
    /// </summary>
    public partial class MicrosoftDynamicsCRMRetrieveEntityResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMRetrieveEntityResponse class.
        /// </summary>
        public MicrosoftDynamicsCRMRetrieveEntityResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMRetrieveEntityResponse class.
        /// </summary>
        public MicrosoftDynamicsCRMRetrieveEntityResponse(MicrosoftDynamicsCRMComplexEntityMetadata entityMetadata = default(MicrosoftDynamicsCRMComplexEntityMetadata))
        {
            EntityMetadata = entityMetadata;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EntityMetadata")]
        public MicrosoftDynamicsCRMComplexEntityMetadata EntityMetadata { get; set; }

    }
}
