// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Embc.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq; using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// RecentItem
    /// </summary>
    public partial class MicrosoftDynamicsCRMRecentItem
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftDynamicsCRMRecentItem
        /// class.
        /// </summary>
        public MicrosoftDynamicsCRMRecentItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftDynamicsCRMRecentItem
        /// class.
        /// </summary>
        /// <param name="recordType">Possible values include: 'Entity', 'Grid',
        /// 'Isv', 'Invalid'</param>
        public MicrosoftDynamicsCRMRecentItem(string displayName = default(string), string iconPath = default(string), string lastAccessedStr = default(string), string entityTypeName = default(string), string objectId = default(string), bool? pinStatus = default(bool?), string recordType = default(string), bool? isUserView = default(bool?), string title = default(string), bool? isDeleted = default(bool?))
        {
            DisplayName = displayName;
            IconPath = iconPath;
            LastAccessedStr = lastAccessedStr;
            EntityTypeName = entityTypeName;
            ObjectId = objectId;
            PinStatus = pinStatus;
            RecordType = recordType;
            IsUserView = isUserView;
            Title = title;
            IsDeleted = isDeleted;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DisplayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IconPath")]
        public string IconPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastAccessedStr")]
        public string LastAccessedStr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EntityTypeName")]
        public string EntityTypeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ObjectId")]
        public string ObjectId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PinStatus")]
        public bool? PinStatus { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Entity', 'Grid', 'Isv',
        /// 'Invalid'
        /// </summary>
        [JsonProperty(PropertyName = "RecordType")]
        public string RecordType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsUserView")]
        public bool? IsUserView { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsDeleted")]
        public bool? IsDeleted { get; set; }

    }
}
