// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Embc.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq; using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// systemuserprofiles
    /// </summary>
    public partial class MicrosoftDynamicsCRMsystemuserprofiles
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMsystemuserprofiles class.
        /// </summary>
        public MicrosoftDynamicsCRMsystemuserprofiles()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMsystemuserprofiles class.
        /// </summary>
        public MicrosoftDynamicsCRMsystemuserprofiles(string systemuserprofileid = default(string), long? versionnumber = default(long?), string systemuserid = default(string), string fieldsecurityprofileid = default(string))
        {
            Systemuserprofileid = systemuserprofileid;
            Versionnumber = versionnumber;
            Systemuserid = systemuserid;
            Fieldsecurityprofileid = fieldsecurityprofileid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemuserprofileid")]
        public string Systemuserprofileid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "versionnumber")]
        public long? Versionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemuserid")]
        public string Systemuserid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fieldsecurityprofileid")]
        public string Fieldsecurityprofileid { get; set; }

    }
}
