// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Embc.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq; using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// LookupMetadata
    /// </summary>
    public partial class MicrosoftDynamicsCRMLookupMetadata
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMLookupMetadata class.
        /// </summary>
        public MicrosoftDynamicsCRMLookupMetadata()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMLookupMetadata class.
        /// </summary>
        public MicrosoftDynamicsCRMLookupMetadata(MicrosoftDynamicsCRMLookupEntityMetadata entity = default(MicrosoftDynamicsCRMLookupEntityMetadata), MicrosoftDynamicsCRMLookupView view = default(MicrosoftDynamicsCRMLookupView))
        {
            Entity = entity;
            View = view;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Entity")]
        public MicrosoftDynamicsCRMLookupEntityMetadata Entity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "View")]
        public MicrosoftDynamicsCRMLookupView View { get; set; }

    }
}
