// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Embc.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq; using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// QueryByAttribute
    /// </summary>
    public partial class MicrosoftDynamicsCRMQueryByAttribute
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMQueryByAttribute class.
        /// </summary>
        public MicrosoftDynamicsCRMQueryByAttribute()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMQueryByAttribute class.
        /// </summary>
        public MicrosoftDynamicsCRMQueryByAttribute(string entityName = default(string), IList<string> attributes = default(IList<string>), IList<MicrosoftDynamicsCRMObject> values = default(IList<MicrosoftDynamicsCRMObject>), MicrosoftDynamicsCRMPagingInfo pageInfo = default(MicrosoftDynamicsCRMPagingInfo), MicrosoftDynamicsCRMColumnSet columnSet = default(MicrosoftDynamicsCRMColumnSet), IList<MicrosoftDynamicsCRMOrderExpression> orders = default(IList<MicrosoftDynamicsCRMOrderExpression>), int? topCount = default(int?))
        {
            EntityName = entityName;
            Attributes = attributes;
            Values = values;
            PageInfo = pageInfo;
            ColumnSet = columnSet;
            Orders = orders;
            TopCount = topCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EntityName")]
        public string EntityName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attributes")]
        [NotMapped] public IList<string> Attributes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Values")]
        [NotMapped] public IList<MicrosoftDynamicsCRMObject> Values { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PageInfo")]
        public MicrosoftDynamicsCRMPagingInfo PageInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ColumnSet")]
        public MicrosoftDynamicsCRMColumnSet ColumnSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Orders")]
        [NotMapped] public IList<MicrosoftDynamicsCRMOrderExpression> Orders { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TopCount")]
        public int? TopCount { get; set; }

    }
}
