version: "3.6"

services:
  embc-pdf:
    build:
      context: .
      dockerfile: Dockerfile
    image: embc-pdf
    container_name: embc-pdf
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/usr/src/app/src/
      - ./test:/usr/src/app/test/
    command: npm run debug
    environment:
      - NODE_ENV=development
      - PORT
      - IP
      - MAX_PAYLOAD_SIZE
      - ENABLE_CORS
      - ENABLE_DIAGNOSTICS
